spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

logging:
  level:
    ROOT: INFO